//! Skin timer identifiers, extracted from the reference implementation's `SkinProperty.java`.
//!
//! Generated by `tools/gen-skin-timer.rs`. Do not edit by hand: `timer_table_checksum_matches`
//! in `crates/rbms-skin/src/timer/tests.rs` re-derives [`TIMER_TABLE_CHECKSUM`] from
//! [`ALL_TIMER`], and a hand edit that touches one without the other fails it.

use crate::timer::TimerId;

/// Every extracted declaration as `(id, name)` in source order. The `TIMER_` prefix is stripped, so
/// each name matches its constant in [`timer_id`].
pub const ALL_TIMER: &[(i32, &str)] = &[
    (1, "STARTINPUT"),
    (2, "FADEOUT"),
    (3, "FAILED"),
    (10, "SONGBAR_MOVE"),
    (11, "SONGBAR_CHANGE"),
    (12, "SONGBAR_MOVE_UP"),
    (13, "SONGBAR_MOVE_DOWN"),
    (14, "SONGBAR_STOP"),
    (15, "README_BEGIN"),
    (16, "README_END"),
    (21, "PANEL1_ON"),
    (22, "PANEL2_ON"),
    (23, "PANEL3_ON"),
    (24, "PANEL4_ON"),
    (25, "PANEL5_ON"),
    (26, "PANEL6_ON"),
    (31, "PANEL1_OFF"),
    (32, "PANEL2_OFF"),
    (33, "PANEL3_OFF"),
    (34, "PANEL4_OFF"),
    (35, "PANEL5_OFF"),
    (36, "PANEL6_OFF"),
    (40, "READY"),
    (41, "PLAY"),
    (42, "GAUGE_INCLEASE_1P"),
    (43, "GAUGE_INCLEASE_2P"),
    (44, "GAUGE_MAX_1P"),
    (45, "GAUGE_MAX_2P"),
    (46, "JUDGE_1P"),
    (47, "JUDGE_2P"),
    (247, "JUDGE_3P"),
    (446, "COMBO_1P"),
    (447, "COMBO_2P"),
    (448, "COMBO_3P"),
    (48, "FULLCOMBO_1P"),
    (348, "SCORE_A"),
    (349, "SCORE_AA"),
    (350, "SCORE_AAA"),
    (351, "SCORE_BEST"),
    (352, "SCORE_TARGET"),
    (49, "FULLCOMBO_2P"),
    (50, "BOMB_1P_SCRATCH"),
    (51, "BOMB_1P_KEY1"),
    (250, "HCN_ACTIVE_1P_SCRATCH"),
    (251, "HCN_ACTIVE_1P_KEY1"),
    (52, "BOMB_1P_KEY2"),
    (53, "BOMB_1P_KEY3"),
    (54, "BOMB_1P_KEY4"),
    (55, "BOMB_1P_KEY5"),
    (56, "BOMB_1P_KEY6"),
    (57, "BOMB_1P_KEY7"),
    (58, "BOMB_1P_KEY8"),
    (59, "BOMB_1P_KEY9"),
    (60, "BOMB_2P_SCRATCH"),
    (61, "BOMB_2P_KEY1"),
    (62, "BOMB_2P_KEY2"),
    (63, "BOMB_2P_KEY3"),
    (64, "BOMB_2P_KEY4"),
    (65, "BOMB_2P_KEY5"),
    (66, "BOMB_2P_KEY6"),
    (67, "BOMB_2P_KEY7"),
    (68, "BOMB_2P_KEY8"),
    (69, "BOMB_2P_KEY9"),
    (70, "HOLD_1P_SCRATCH"),
    (71, "HOLD_1P_KEY1"),
    (270, "HCN_DAMAGE_1P_SCRATCH"),
    (271, "HCN_DAMAGE_1P_KEY1"),
    (80, "HOLD_2P_SCRATCH"),
    (81, "HOLD_2P_KEY1"),
    (100, "KEYON_1P_SCRATCH"),
    (101, "KEYON_1P_KEY1"),
    (102, "KEYON_1P_KEY2"),
    (103, "KEYON_1P_KEY3"),
    (104, "KEYON_1P_KEY4"),
    (105, "KEYON_1P_KEY5"),
    (106, "KEYON_1P_KEY6"),
    (107, "KEYON_1P_KEY7"),
    (108, "KEYON_1P_KEY8"),
    (109, "KEYON_1P_KEY9"),
    (110, "KEYON_2P_SCRATCH"),
    (111, "KEYON_2P_KEY1"),
    (112, "KEYON_2P_KEY2"),
    (113, "KEYON_2P_KEY3"),
    (114, "KEYON_2P_KEY4"),
    (115, "KEYON_2P_KEY5"),
    (116, "KEYON_2P_KEY6"),
    (117, "KEYON_2P_KEY7"),
    (118, "KEYON_2P_KEY8"),
    (119, "KEYON_2P_KEY9"),
    (120, "KEYOFF_1P_SCRATCH"),
    (121, "KEYOFF_1P_KEY1"),
    (122, "KEYOFF_1P_KEY2"),
    (123, "KEYOFF_1P_KEY3"),
    (124, "KEYOFF_1P_KEY4"),
    (125, "KEYOFF_1P_KEY5"),
    (126, "KEYOFF_1P_KEY6"),
    (127, "KEYOFF_1P_KEY7"),
    (128, "KEYOFF_1P_KEY8"),
    (129, "KEYOFF_1P_KEY9"),
    (130, "KEYOFF_2P_SCRATCH"),
    (131, "KEYOFF_2P_KEY1"),
    (132, "KEYOFF_2P_KEY2"),
    (133, "KEYOFF_2P_KEY3"),
    (134, "KEYOFF_2P_KEY4"),
    (135, "KEYOFF_2P_KEY5"),
    (136, "KEYOFF_2P_KEY6"),
    (137, "KEYOFF_2P_KEY7"),
    (138, "KEYOFF_2P_KEY8"),
    (139, "KEYOFF_2P_KEY9"),
    (140, "RHYTHM"),
    (143, "ENDOFNOTE_1P"),
    (144, "ENDOFNOTE_2P"),
    (150, "RESULTGRAPH_BEGIN"),
    (151, "RESULTGRAPH_END"),
    (152, "RESULT_UPDATESCORE"),
    (172, "IR_CONNECT_BEGIN"),
    (173, "IR_CONNECT_SUCCESS"),
    (174, "IR_CONNECT_FAIL"),
    (900, "PM_CHARA_1P_NEUTRAL"),
    (901, "PM_CHARA_1P_FEVER"),
    (902, "PM_CHARA_1P_GREAT"),
    (903, "PM_CHARA_1P_GOOD"),
    (904, "PM_CHARA_1P_BAD"),
    (905, "PM_CHARA_2P_NEUTRAL"),
    (906, "PM_CHARA_2P_GREAT"),
    (907, "PM_CHARA_2P_BAD"),
    (908, "MUSIC_END"),
    (909, "PM_CHARA_DANCE"),
    (1010, "BOMB_1P_KEY10"),
    (1099, "BOMB_1P_KEY99"),
    (1110, "BOMB_2P_KEY10"),
    (1199, "BOMB_2P_KEY99"),
    (1210, "HOLD_1P_KEY10"),
    (1299, "HOLD_1P_KEY99"),
    (1310, "HOLD_2P_KEY10"),
    (1399, "HOLD_2P_KEY99"),
    (1410, "KEYON_1P_KEY10"),
    (1499, "KEYON_1P_KEY99"),
    (1510, "KEYON_2P_KEY10"),
    (1599, "KEYON_2P_KEY99"),
    (1610, "KEYOFF_1P_KEY10"),
    (1699, "KEYOFF_1P_KEY99"),
    (1710, "KEYOFF_2P_KEY10"),
    (1799, "KEYOFF_2P_KEY99"),
    (1810, "HCN_ACTIVE_1P_KEY10"),
    (1910, "HCN_ACTIVE_2P_KEY10"),
    (2010, "HCN_DAMAGE_1P_KEY10"),
    (2110, "HCN_DAMAGE_2P_KEY10"),
    (2999, "MAX"),
    (10000, "CUSTOM_BEGIN"),
    (19999, "CUSTOM_END"),
];

/// How many `TIMER_*` declarations the reference source holds. Part of the per-prefix total the
/// property table checks against the whole constant count.
pub const TIMER_CONSTANT_COUNT: usize = 151;

/// FNV-1a 64 over the `NAME=VALUE` lines of [`ALL_TIMER`] in order.
pub const TIMER_TABLE_CHECKSUM: u64 = 0xb7d269c6181e8e57;

/// The extracted identifiers, one typed constant each.
pub mod timer_id {
    use super::TimerId;

    pub const STARTINPUT: TimerId = TimerId(1);
    pub const FADEOUT: TimerId = TimerId(2);
    pub const FAILED: TimerId = TimerId(3);
    pub const SONGBAR_MOVE: TimerId = TimerId(10);
    pub const SONGBAR_CHANGE: TimerId = TimerId(11);
    pub const SONGBAR_MOVE_UP: TimerId = TimerId(12);
    pub const SONGBAR_MOVE_DOWN: TimerId = TimerId(13);
    pub const SONGBAR_STOP: TimerId = TimerId(14);
    pub const README_BEGIN: TimerId = TimerId(15);
    pub const README_END: TimerId = TimerId(16);
    pub const PANEL1_ON: TimerId = TimerId(21);
    pub const PANEL2_ON: TimerId = TimerId(22);
    pub const PANEL3_ON: TimerId = TimerId(23);
    pub const PANEL4_ON: TimerId = TimerId(24);
    pub const PANEL5_ON: TimerId = TimerId(25);
    pub const PANEL6_ON: TimerId = TimerId(26);
    pub const PANEL1_OFF: TimerId = TimerId(31);
    pub const PANEL2_OFF: TimerId = TimerId(32);
    pub const PANEL3_OFF: TimerId = TimerId(33);
    pub const PANEL4_OFF: TimerId = TimerId(34);
    pub const PANEL5_OFF: TimerId = TimerId(35);
    pub const PANEL6_OFF: TimerId = TimerId(36);
    pub const READY: TimerId = TimerId(40);
    pub const PLAY: TimerId = TimerId(41);
    pub const GAUGE_INCLEASE_1P: TimerId = TimerId(42);
    pub const GAUGE_INCLEASE_2P: TimerId = TimerId(43);
    pub const GAUGE_MAX_1P: TimerId = TimerId(44);
    pub const GAUGE_MAX_2P: TimerId = TimerId(45);
    pub const JUDGE_1P: TimerId = TimerId(46);
    pub const JUDGE_2P: TimerId = TimerId(47);
    pub const JUDGE_3P: TimerId = TimerId(247);
    pub const COMBO_1P: TimerId = TimerId(446);
    pub const COMBO_2P: TimerId = TimerId(447);
    pub const COMBO_3P: TimerId = TimerId(448);
    pub const FULLCOMBO_1P: TimerId = TimerId(48);
    pub const SCORE_A: TimerId = TimerId(348);
    pub const SCORE_AA: TimerId = TimerId(349);
    pub const SCORE_AAA: TimerId = TimerId(350);
    pub const SCORE_BEST: TimerId = TimerId(351);
    pub const SCORE_TARGET: TimerId = TimerId(352);
    pub const FULLCOMBO_2P: TimerId = TimerId(49);
    pub const BOMB_1P_SCRATCH: TimerId = TimerId(50);
    pub const BOMB_1P_KEY1: TimerId = TimerId(51);
    pub const HCN_ACTIVE_1P_SCRATCH: TimerId = TimerId(250);
    pub const HCN_ACTIVE_1P_KEY1: TimerId = TimerId(251);
    pub const BOMB_1P_KEY2: TimerId = TimerId(52);
    pub const BOMB_1P_KEY3: TimerId = TimerId(53);
    pub const BOMB_1P_KEY4: TimerId = TimerId(54);
    pub const BOMB_1P_KEY5: TimerId = TimerId(55);
    pub const BOMB_1P_KEY6: TimerId = TimerId(56);
    pub const BOMB_1P_KEY7: TimerId = TimerId(57);
    pub const BOMB_1P_KEY8: TimerId = TimerId(58);
    pub const BOMB_1P_KEY9: TimerId = TimerId(59);
    pub const BOMB_2P_SCRATCH: TimerId = TimerId(60);
    pub const BOMB_2P_KEY1: TimerId = TimerId(61);
    pub const BOMB_2P_KEY2: TimerId = TimerId(62);
    pub const BOMB_2P_KEY3: TimerId = TimerId(63);
    pub const BOMB_2P_KEY4: TimerId = TimerId(64);
    pub const BOMB_2P_KEY5: TimerId = TimerId(65);
    pub const BOMB_2P_KEY6: TimerId = TimerId(66);
    pub const BOMB_2P_KEY7: TimerId = TimerId(67);
    pub const BOMB_2P_KEY8: TimerId = TimerId(68);
    pub const BOMB_2P_KEY9: TimerId = TimerId(69);
    pub const HOLD_1P_SCRATCH: TimerId = TimerId(70);
    pub const HOLD_1P_KEY1: TimerId = TimerId(71);
    pub const HCN_DAMAGE_1P_SCRATCH: TimerId = TimerId(270);
    pub const HCN_DAMAGE_1P_KEY1: TimerId = TimerId(271);
    pub const HOLD_2P_SCRATCH: TimerId = TimerId(80);
    pub const HOLD_2P_KEY1: TimerId = TimerId(81);
    pub const KEYON_1P_SCRATCH: TimerId = TimerId(100);
    pub const KEYON_1P_KEY1: TimerId = TimerId(101);
    pub const KEYON_1P_KEY2: TimerId = TimerId(102);
    pub const KEYON_1P_KEY3: TimerId = TimerId(103);
    pub const KEYON_1P_KEY4: TimerId = TimerId(104);
    pub const KEYON_1P_KEY5: TimerId = TimerId(105);
    pub const KEYON_1P_KEY6: TimerId = TimerId(106);
    pub const KEYON_1P_KEY7: TimerId = TimerId(107);
    pub const KEYON_1P_KEY8: TimerId = TimerId(108);
    pub const KEYON_1P_KEY9: TimerId = TimerId(109);
    pub const KEYON_2P_SCRATCH: TimerId = TimerId(110);
    pub const KEYON_2P_KEY1: TimerId = TimerId(111);
    pub const KEYON_2P_KEY2: TimerId = TimerId(112);
    pub const KEYON_2P_KEY3: TimerId = TimerId(113);
    pub const KEYON_2P_KEY4: TimerId = TimerId(114);
    pub const KEYON_2P_KEY5: TimerId = TimerId(115);
    pub const KEYON_2P_KEY6: TimerId = TimerId(116);
    pub const KEYON_2P_KEY7: TimerId = TimerId(117);
    pub const KEYON_2P_KEY8: TimerId = TimerId(118);
    pub const KEYON_2P_KEY9: TimerId = TimerId(119);
    pub const KEYOFF_1P_SCRATCH: TimerId = TimerId(120);
    pub const KEYOFF_1P_KEY1: TimerId = TimerId(121);
    pub const KEYOFF_1P_KEY2: TimerId = TimerId(122);
    pub const KEYOFF_1P_KEY3: TimerId = TimerId(123);
    pub const KEYOFF_1P_KEY4: TimerId = TimerId(124);
    pub const KEYOFF_1P_KEY5: TimerId = TimerId(125);
    pub const KEYOFF_1P_KEY6: TimerId = TimerId(126);
    pub const KEYOFF_1P_KEY7: TimerId = TimerId(127);
    pub const KEYOFF_1P_KEY8: TimerId = TimerId(128);
    pub const KEYOFF_1P_KEY9: TimerId = TimerId(129);
    pub const KEYOFF_2P_SCRATCH: TimerId = TimerId(130);
    pub const KEYOFF_2P_KEY1: TimerId = TimerId(131);
    pub const KEYOFF_2P_KEY2: TimerId = TimerId(132);
    pub const KEYOFF_2P_KEY3: TimerId = TimerId(133);
    pub const KEYOFF_2P_KEY4: TimerId = TimerId(134);
    pub const KEYOFF_2P_KEY5: TimerId = TimerId(135);
    pub const KEYOFF_2P_KEY6: TimerId = TimerId(136);
    pub const KEYOFF_2P_KEY7: TimerId = TimerId(137);
    pub const KEYOFF_2P_KEY8: TimerId = TimerId(138);
    pub const KEYOFF_2P_KEY9: TimerId = TimerId(139);
    pub const RHYTHM: TimerId = TimerId(140);
    pub const ENDOFNOTE_1P: TimerId = TimerId(143);
    pub const ENDOFNOTE_2P: TimerId = TimerId(144);
    pub const RESULTGRAPH_BEGIN: TimerId = TimerId(150);
    pub const RESULTGRAPH_END: TimerId = TimerId(151);
    pub const RESULT_UPDATESCORE: TimerId = TimerId(152);
    pub const IR_CONNECT_BEGIN: TimerId = TimerId(172);
    pub const IR_CONNECT_SUCCESS: TimerId = TimerId(173);
    pub const IR_CONNECT_FAIL: TimerId = TimerId(174);
    pub const PM_CHARA_1P_NEUTRAL: TimerId = TimerId(900);
    pub const PM_CHARA_1P_FEVER: TimerId = TimerId(901);
    pub const PM_CHARA_1P_GREAT: TimerId = TimerId(902);
    pub const PM_CHARA_1P_GOOD: TimerId = TimerId(903);
    pub const PM_CHARA_1P_BAD: TimerId = TimerId(904);
    pub const PM_CHARA_2P_NEUTRAL: TimerId = TimerId(905);
    pub const PM_CHARA_2P_GREAT: TimerId = TimerId(906);
    pub const PM_CHARA_2P_BAD: TimerId = TimerId(907);
    pub const MUSIC_END: TimerId = TimerId(908);
    pub const PM_CHARA_DANCE: TimerId = TimerId(909);
    pub const BOMB_1P_KEY10: TimerId = TimerId(1010);
    pub const BOMB_1P_KEY99: TimerId = TimerId(1099);
    pub const BOMB_2P_KEY10: TimerId = TimerId(1110);
    pub const BOMB_2P_KEY99: TimerId = TimerId(1199);
    pub const HOLD_1P_KEY10: TimerId = TimerId(1210);
    pub const HOLD_1P_KEY99: TimerId = TimerId(1299);
    pub const HOLD_2P_KEY10: TimerId = TimerId(1310);
    pub const HOLD_2P_KEY99: TimerId = TimerId(1399);
    pub const KEYON_1P_KEY10: TimerId = TimerId(1410);
    pub const KEYON_1P_KEY99: TimerId = TimerId(1499);
    pub const KEYON_2P_KEY10: TimerId = TimerId(1510);
    pub const KEYON_2P_KEY99: TimerId = TimerId(1599);
    pub const KEYOFF_1P_KEY10: TimerId = TimerId(1610);
    pub const KEYOFF_1P_KEY99: TimerId = TimerId(1699);
    pub const KEYOFF_2P_KEY10: TimerId = TimerId(1710);
    pub const KEYOFF_2P_KEY99: TimerId = TimerId(1799);
    pub const HCN_ACTIVE_1P_KEY10: TimerId = TimerId(1810);
    pub const HCN_ACTIVE_2P_KEY10: TimerId = TimerId(1910);
    pub const HCN_DAMAGE_1P_KEY10: TimerId = TimerId(2010);
    pub const HCN_DAMAGE_2P_KEY10: TimerId = TimerId(2110);
    pub const MAX: TimerId = TimerId(2999);
    pub const CUSTOM_BEGIN: TimerId = TimerId(10000);
    pub const CUSTOM_END: TimerId = TimerId(19999);
}
