[package]
name = "rbms-render"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rbms-model = { workspace = true }
rbms-chart = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
thiserror = { workspace = true }
cosmic-text = "0.19.0"

[dev-dependencies]
rbms-parser = { workspace = true }

[lints]
workspace = true
