//! The generated property constant table, extracted from the reference implementation's
//! `SkinProperty.java`.
//!
//! Generated by `tools/gen-skin-property.rs` and committed as-is; never edited by hand. The
//! submodules are split by the registry kind that reads them, and every constant is re-exported
//! here so a caller names one module rather than five.
//!
//! `TIMER_*` lives in [`crate::timer`] instead, generated by its own tool. The two tables
//! together account for every declaration in the source, which
//! `property_table_covers_every_declaration` checks against [`REFERENCE_CONSTANT_COUNT`].

pub mod boolean;
pub mod float;
pub mod integer;
pub mod misc;
pub mod text;

pub use boolean::*;
pub use float::*;
pub use integer::*;
pub use misc::*;
pub use text::*;

/// How many `OPTION_*` declarations the reference source holds.
pub const OPTION_CONSTANT_COUNT: usize = 287;

/// How many `NUMBER_*` declarations the reference source holds.
pub const NUMBER_CONSTANT_COUNT: usize = 273;

/// How many `RATE_*` declarations the reference source holds.
pub const RATE_CONSTANT_COUNT: usize = 30;

/// How many `SLIDER_*` declarations the reference source holds.
pub const SLIDER_CONSTANT_COUNT: usize = 9;

/// How many `BARGRAPH_*` declarations the reference source holds.
pub const BARGRAPH_CONSTANT_COUNT: usize = 22;

/// How many `FLOAT_*` declarations the reference source holds.
pub const FLOAT_CONSTANT_COUNT: usize = 40;

/// How many `STRING_*` declarations the reference source holds.
pub const STRING_CONSTANT_COUNT: usize = 43;

/// How many `BUTTON_*` declarations the reference source holds.
pub const BUTTON_CONSTANT_COUNT: usize = 74;

/// How many `OFFSET_*` declarations the reference source holds.
pub const OFFSET_CONSTANT_COUNT: usize = 16;

/// How many `VALUE_*` declarations the reference source holds.
pub const VALUE_CONSTANT_COUNT: usize = 16;

/// How many `IMAGE_*` declarations the reference source holds.
pub const IMAGE_CONSTANT_COUNT: usize = 5;

/// How many `EVENT_*` declarations the reference source holds.
pub const EVENT_CONSTANT_COUNT: usize = 2;

/// How many non-timer declarations the reference source holds, the sum of the per-prefix counts.
pub const PROPERTY_CONSTANT_COUNT: usize = 817;

/// How many `public static final int` declarations the reference source holds in total, timers
/// included. [`PROPERTY_CONSTANT_COUNT`] plus [`crate::timer::TIMER_CONSTANT_COUNT`] must equal it.
pub const REFERENCE_CONSTANT_COUNT: usize = 968;

/// Every emitted table with its prefix, in the order [`PROPERTY_TABLE_CHECKSUM`] hashes them.
pub const ALL_PROPERTY_TABLES: &[(&str, &[(i32, &str)])] = &[
    ("OPTION", ALL_OPTION),
    ("NUMBER", ALL_NUMBER),
    ("RATE", ALL_RATE),
    ("SLIDER", ALL_SLIDER),
    ("BARGRAPH", ALL_BARGRAPH),
    ("FLOAT", ALL_FLOAT),
    ("STRING", ALL_STRING),
    ("BUTTON", ALL_BUTTON),
    ("OFFSET", ALL_OFFSET),
    ("VALUE", ALL_VALUE),
    ("IMAGE", ALL_IMAGE),
    ("EVENT", ALL_EVENT),
];

/// FNV-1a 64 over the `NAME=VALUE` lines of [`ALL_PROPERTY_TABLES`], table by table and in
/// order within each.
pub const PROPERTY_TABLE_CHECKSUM: u64 = 0x4d64eaf3bb954b86;
