//! The generated property constant table, extracted from the reference implementation's
//! `SkinProperty.java`.
//!
//! Generated by `tools/gen-skin-property.rs` and committed as-is; never edited by hand. The
//! submodules are split by the registry kind that reads them, and every constant is re-exported
//! here so a caller names one module rather than five.
//!
//! `TIMER_*` lives in [`crate::timer`] instead, generated by its own tool. The two tables
//! together account for every declaration in the source, which
//! `property_table_covers_every_declaration` checks against [`REFERENCE_CONSTANT_COUNT`].

pub mod boolean;
pub mod float;
pub mod integer;
pub mod misc;
pub mod names;
pub mod text;

pub use boolean::*;
pub use float::*;
pub use integer::*;
pub use misc::*;
pub use names::*;
pub use text::*;

/// How many `OPTION_*` declarations the reference source holds.
pub const OPTION_CONSTANT_COUNT: usize = 287;

/// How many `NUMBER_*` declarations the reference source holds.
pub const NUMBER_CONSTANT_COUNT: usize = 273;

/// How many `RATE_*` declarations the reference source holds.
pub const RATE_CONSTANT_COUNT: usize = 30;

/// How many `SLIDER_*` declarations the reference source holds.
pub const SLIDER_CONSTANT_COUNT: usize = 9;

/// How many `BARGRAPH_*` declarations the reference source holds.
pub const BARGRAPH_CONSTANT_COUNT: usize = 22;

/// How many `FLOAT_*` declarations the reference source holds.
pub const FLOAT_CONSTANT_COUNT: usize = 40;

/// How many `STRING_*` declarations the reference source holds.
pub const STRING_CONSTANT_COUNT: usize = 43;

/// How many `BUTTON_*` declarations the reference source holds.
pub const BUTTON_CONSTANT_COUNT: usize = 74;

/// How many `OFFSET_*` declarations the reference source holds.
pub const OFFSET_CONSTANT_COUNT: usize = 16;

/// How many `VALUE_*` declarations the reference source holds.
pub const VALUE_CONSTANT_COUNT: usize = 16;

/// How many `IMAGE_*` declarations the reference source holds.
pub const IMAGE_CONSTANT_COUNT: usize = 5;

/// How many `EVENT_*` declarations the reference source holds.
pub const EVENT_CONSTANT_COUNT: usize = 2;

/// How many non-timer declarations the reference source holds, the sum of the per-prefix counts.
pub const PROPERTY_CONSTANT_COUNT: usize = 817;

/// How many `public static final int` declarations the reference source holds in total, timers
/// included. [`PROPERTY_CONSTANT_COUNT`] plus [`crate::timer::TIMER_CONSTANT_COUNT`] must equal it.
pub const REFERENCE_CONSTANT_COUNT: usize = 968;

/// Every emitted table with its prefix, in the order [`PROPERTY_TABLE_CHECKSUM`] hashes them.
pub const ALL_PROPERTY_TABLES: &[(&str, &[(i32, &str)])] = &[
    ("OPTION", ALL_OPTION),
    ("NUMBER", ALL_NUMBER),
    ("RATE", ALL_RATE),
    ("SLIDER", ALL_SLIDER),
    ("BARGRAPH", ALL_BARGRAPH),
    ("FLOAT", ALL_FLOAT),
    ("STRING", ALL_STRING),
    ("BUTTON", ALL_BUTTON),
    ("OFFSET", ALL_OFFSET),
    ("VALUE", ALL_VALUE),
    ("IMAGE", ALL_IMAGE),
    ("EVENT", ALL_EVENT),
];

/// FNV-1a 64 over the `NAME=VALUE` lines of [`ALL_PROPERTY_TABLES`], table by table and in
/// order within each.
pub const PROPERTY_TABLE_CHECKSUM: u64 = 0x4d64eaf3bb954b86;

/// How many constants the reference's `BooleanType` enum holds.
pub const BOOLEAN_NAME_COUNT: usize = 216;

/// How many constants the reference's `ValueType` enum holds.
pub const INTEGER_NAME_COUNT: usize = 148;

/// How many constants the reference's `IndexType` enum holds.
pub const IMAGE_INDEX_NAME_COUNT: usize = 62;

/// How many constants the reference's `RateType` enum holds.
pub const RATE_NAME_COUNT: usize = 31;

/// How many constants the reference's `FloatType` enum holds.
pub const FLOAT_NAME_COUNT: usize = 29;

/// How many constants the reference's `StringType` enum holds.
pub const STRING_NAME_COUNT: usize = 26;

/// How many constants the reference's `EventType` enum holds.
pub const EVENT_NAME_COUNT: usize = 54;

/// Every emitted name table with its stem, in the order [`NAME_TABLE_CHECKSUM`] hashes them.
pub const ALL_NAME_TABLES: &[(&str, &[(i32, &str)])] = &[
    ("BOOLEAN", ALL_BOOLEAN_NAME),
    ("INTEGER", ALL_INTEGER_NAME),
    ("IMAGE_INDEX", ALL_IMAGE_INDEX_NAME),
    ("RATE", ALL_RATE_NAME),
    ("FLOAT", ALL_FLOAT_NAME),
    ("STRING", ALL_STRING_NAME),
    ("EVENT", ALL_EVENT_NAME),
];

/// Every emitted stillness list with its name, in the order [`NAME_TABLE_CHECKSUM`] hashes them.
pub const ALL_STATIC_LISTS: &[(&str, &[i32])] =
    &[("STATIC_OUTSIDE_SELECT", STATIC_OUTSIDE_SELECT), ("STATIC_ON_RESULT", STATIC_ON_RESULT), ("STATIC_ALWAYS", STATIC_ALWAYS)];

/// Every emitted writer list with its name, in the order [`NAME_TABLE_CHECKSUM`] hashes them.
pub const ALL_WRITER_LISTS: &[(&str, &[i32])] = &[("WRITABLE_RATES", WRITABLE_RATES), ("WRITABLE_STRINGS", WRITABLE_STRINGS)];

/// FNV-1a 64 over the `STEM:name=id` lines of [`ALL_NAME_TABLES`] followed by the `LIST=id` lines
/// of [`ALL_STATIC_LISTS`] and of [`ALL_WRITER_LISTS`], each in order.
pub const NAME_TABLE_CHECKSUM: u64 = 0x738a4ba1021efcb0;
