export const ERROR_CODE = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    RATE_LIMITED: 'RATE_LIMITED',
    SERVICE_NOT_CONFIGURED: 'SERVICE_NOT_CONFIGURED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    IR_CHART_NOT_FOUND: 'IR_CHART_NOT_FOUND',
    IR_PLAYER_NOT_FOUND: 'IR_PLAYER_NOT_FOUND',
    IR_SCORE_NOT_FOUND: 'IR_SCORE_NOT_FOUND',
    IR_REPLAY_NOT_FOUND: 'IR_REPLAY_NOT_FOUND',
    IR_SETTING_NOT_FOUND: 'IR_SETTING_NOT_FOUND',
    IR_COURSE_NOT_FOUND: 'IR_COURSE_NOT_FOUND',
    IR_TABLE_NOT_FOUND: 'IR_TABLE_NOT_FOUND',
    IR_ACCOUNT_EXISTS: 'IR_ACCOUNT_EXISTS',
    IR_PAYLOAD_TOO_LARGE: 'IR_PAYLOAD_TOO_LARGE',
    IR_API_VERSION_UNSUPPORTED: 'IR_API_VERSION_UNSUPPORTED',
} as const

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE]
