//! Generates `crates/rbms-skin/src/timer/generated.rs` from the reference implementation's
//! `SkinProperty.java`.
//!
//! The reference tree is not part of this repository, so this runs by hand and its output is
//! committed. Build and run it with:
//!
//! ```text
//! rustc -O tools/gen-skin-timer.rs -o target/gen-skin-timer
//! target/gen-skin-timer <path to SkinProperty.java> crates/rbms-skin/src/timer/generated.rs
//! ```
//!
//! It extracts every `public static final int TIMER_<NAME> = <n>;` declaration in source order and
//! emits typed [`TimerId`] constants, an index array, the declaration count and an FNV-1a checksum
//! over the table. A test in the generated crate re-derives that checksum, so a hand edit that
//! desynchronises the table from the index array fails the build.

use std::fmt::Write as _;

/// The declaration prefix every extracted constant carries in the reference source.
const DECLARATION: &str = "public static final int ";

/// The name prefix that marks a timer identifier among the reference constants.
const TIMER_PREFIX: &str = "TIMER_";

/// FNV-1a 64-bit offset basis, matching the signature hashing already used by `rbms-render`.
const FNV_OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;

/// FNV-1a 64-bit prime.
const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;

/// One extracted `TIMER_*` declaration.
struct Entry {
    name: String,
    value: i32,
}

/// FNV-1a over the `NAME=VALUE` lines of the table, the checksum the generated test re-derives.
fn checksum(entries: &[Entry]) -> u64 {
    let mut hash = FNV_OFFSET_BASIS;
    for entry in entries {
        for byte in format!("{}={}\n", entry.name, entry.value).into_bytes() {
            hash ^= u64::from(byte);
            hash = hash.wrapping_mul(FNV_PRIME);
        }
    }
    hash
}

/// Pulls the `TIMER_*` constants out of the reference source in declaration order.
fn extract(source: &str) -> Result<Vec<Entry>, String> {
    let mut entries: Vec<Entry> = Vec::new();
    for line in source.lines() {
        let Some(rest) = line.trim_start().strip_prefix(DECLARATION) else { continue };
        let Some((name, value)) = rest.split_once('=') else { continue };
        let name = name.trim();
        let Some(name) = name.strip_prefix(TIMER_PREFIX) else { continue };
        let value = value.trim().trim_end_matches(';').trim();
        let value: i32 = value.parse().map_err(|_| format!("{name} has a non-literal value {value}"))?;
        if let Some(previous) = entries.iter().find(|entry| entry.name == name) {
            return Err(format!("{} is declared twice ({} then {})", name, previous.value, value));
        }
        entries.push(Entry { name: name.to_owned(), value });
    }
    if entries.is_empty() { Err("no timer declarations found".to_owned()) } else { Ok(entries) }
}

/// Renders the committed Rust module.
fn render(entries: &[Entry]) -> String {
    let mut out = String::new();
    out.push_str("//! Skin timer identifiers, extracted from the reference implementation's `SkinProperty.java`.\n");
    out.push_str("//!\n");
    out.push_str("//! Generated by `tools/gen-skin-timer.rs`. Do not edit by hand: `timer_table_checksum_matches`\n");
    out.push_str("//! in `crates/rbms-skin/src/timer/tests.rs` re-derives [`TIMER_TABLE_CHECKSUM`] from\n");
    out.push_str("//! [`ALL_TIMER`], and a hand edit that touches one without the other fails it.\n\n");
    out.push_str("use crate::timer::TimerId;\n\n");
    out.push_str("/// Every extracted declaration as `(id, name)` in source order. The `TIMER_` prefix is stripped, so\n");
    out.push_str("/// each name matches its constant in [`timer_id`].\n");
    out.push_str("pub const ALL_TIMER: &[(i32, &str)] = &[\n");
    for entry in entries {
        let _ = writeln!(out, "    ({}, \"{}\"),", entry.value, entry.name);
    }
    out.push_str("];\n\n");
    out.push_str("/// How many `TIMER_*` declarations the reference source holds. Part of the per-prefix total the\n");
    out.push_str("/// property table checks against the whole constant count.\n");
    let _ = writeln!(out, "pub const TIMER_CONSTANT_COUNT: usize = {};\n", entries.len());
    out.push_str("/// FNV-1a 64 over the `NAME=VALUE` lines of [`ALL_TIMER`] in order.\n");
    let _ = writeln!(out, "pub const TIMER_TABLE_CHECKSUM: u64 = {:#018x};\n", checksum(entries));
    out.push_str("/// The extracted identifiers, one typed constant each.\n");
    out.push_str("pub mod timer_id {\n");
    out.push_str("    use super::TimerId;\n\n");
    for entry in entries {
        let _ = writeln!(out, "    pub const {}: TimerId = TimerId({});", entry.name, entry.value);
    }
    out.push_str("}\n");
    out
}

fn main() {
    let mut args = std::env::args().skip(1);
    let Some(input) = args.next() else {
        eprintln!("usage: gen-skin-timer <SkinProperty.java> [output.rs]");
        std::process::exit(2);
    };
    let source = match std::fs::read_to_string(&input) {
        Ok(source) => source,
        Err(error) => {
            eprintln!("cannot read {input}: {error}");
            std::process::exit(1);
        }
    };
    let entries = match extract(&source) {
        Ok(entries) => entries,
        Err(error) => {
            eprintln!("{error}");
            std::process::exit(1);
        }
    };
    let rendered = render(&entries);
    eprintln!("extracted {} timer declarations, checksum {:#018x}", entries.len(), checksum(&entries));
    match args.next() {
        Some(output) => {
            if let Err(error) = std::fs::write(&output, rendered) {
                eprintln!("cannot write {output}: {error}");
                std::process::exit(1);
            }
            eprintln!("wrote {output}");
        }
        None => print!("{rendered}"),
    }
}
