[package]
name = "rbms-video"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["openh264"]
openh264 = ["dep:openh264", "dep:re_mp4"]

[dependencies]
thiserror = { workspace = true }
openh264 = { version = "0.9.8", optional = true }
re_mp4 = { version = "0.5.1", optional = true }

[lints]
workspace = true
